# Site settings
title: Jekyll shop powered by Snipcart
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://192.168.1.65:4000"
url: "http://budgetsurvivalgear.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

port: 4000
host: 0.0.0.0
