# Site settings
title: Jekyll shop powered by Snipcart
email: your-email@domain.com
description: BudgetSurvivalgear.com is your one-stop-shop for affordable survival & prepping gear including fire starters, first aid kits, food supplies, and more. Straight from the source!
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://192.168.1.65:4000"
url: "http://budgetsurvivalgear.com"

permalink: Affordable Survival, Prepping, and Camping Basics » Straight From The Source

# Build settings
markdown: kramdown

port: 4000
host: 0.0.0.0
