- name: Firestarter
  price: 13.99
  slug: firestarter
  description: >
    Gerber Bear small and compact fire starter offers years of use.
    Watertight construction keeps tinder safe and dry, so when
    you need it, you can trust it. This tool has been rigorously
    tested to determine that it will provide a spark for 8000+
    strikes. Take the easily-carried Bear Grylls Fire Starter
    with you no matter where you plan to end up for non-stop
    survival insurance. Lanyard to keep product secure and together.
    Emergency whistle integrated into lanyard cord. Waterproof
    storage compartment for tinder. Land to air rescue instructions
    and SOS. Pocket guide contains Bear’s survival essentials.
  sku: F
  image: http://budgetsurvivalgear.com/img/products/flint-and-steel.jpg
  url: /shop/firemaking/firestarter
  category: Firemaking
  categoryurl: /shop/firemaking

- name: Lighter
  price: 7.99
  slug: lighter
  description: >
    It glows, it floats, and it lights when it's wet!
    Simply put, it's the ultimate lighter! You'll surely want
    one in your survival bag... because you never know when it
    could rain, or when you could drop your lighter in a puddle.
    With the UST Glow-in-the-dark Floating Lighter you don't have
    to worry.
  sku: L
  image: http://budgetsurvivalgear.com/img/products/lighter.jpg
  url: /shop/firemaking/lighter
  category: Firemaking
  categoryurl: /shop/firemaking

- name: Canned ravioli
  price: 0.49
  slug: canned-ravioli
  description: >
    This Chef Boyardee Beef Ravioli, in Tomato & Meat Sauce provides
    a convenient, tasty meal. Chef Boyardee Ravioli features
    raviolis that are stuffed and cooked in tomato and meat sauce.
    Preparation for this beef ravioli in tomato and meat sauce is
    easy - simply heat and serve.
  sku: CR
  image: http://budgetsurvivalgear.com/img/products/canned-ravioli.jpg
  url: /shop/food-and-preparation/canned-ravioli
  category: Food and preparation
  categoryurl: /shop/food-and-preparation

- name: Swiss army knife
  price: 39.99
  slug: swiss-army-knife
  description: >
    When you hear the words Swiss Army Knife, chances are you
    think of the legendary Officer's knife. And that legend
    continues with the Huntsman pocket knife. With the addition
    of scissors and a wood saw, you're ready to cut through just
    about anything. When it's time to go offline and off the
    beaten path, you'll want the Huntsman in your pocket.
  sku: SAK
  image: http://budgetsurvivalgear.com/img/products/swiss-army-knife.jpg
  url: /shop/knives-and-tools/swiss-army-knife
  category: Knives and tools
  categoryurl: /shop/knives-and-tools

- name: First aid kit
  price: 19.99
  slug: first-aid-kit
  description: >
    Compact, durable and water resistant,
    this special edition ‘pink’ first aid
    kit with roll-out compartments is filled
    with practical first aid supplies and
    instructions. An essential item for the
    home, travel or for outdoor activities,
    it is compact enough to fit into a bag
    or backpack making it the perfect gift
    for mums on the go.
  sku: FA
  image: http://budgetsurvivalgear.com/img/products/first-aid-kit.jpg
  url: /shop/first-aid/first-aid-kit
  category: First aid
  categoryurl: /shop/first-aid

- name: Wax jacket
  price: 139.99
  slug: wax-jacket
  description: >
    Crafted in tonal waxed and unwaxed cotton,
    the Kitefin Slim Jacket is part of Barbour's
    exclusive collaboration with Japanese brand
    White Mountaineering. Standout features include
    leather trims, a stowaway hood and an exclusive
    fishing-inspired camo print lining.
  sku: WJ
  image: http://budgetsurvivalgear.com/img/products/wax-jacket.jpg
  url: /shop/clothing-and-gear/wax-jacket/
  category: Clothing and gear
  categoryurl: /shop/clothing-and-gear

- name: Tent
  price: 79.99
  slug: tent
  description: >
    Outwell's usual attention to detail and superb build
    quality help to make it a home away from home - and
    you can make it even more homely by adding the Palm
    Coast 600 footprint for extra durability and insulation,
    the Palm Coast 600 carpet for underfoot comfort and warmth,
    and almost double your sheltered space using the Palm Coast
    600 Front Extension.
  sku: T
  image: http://budgetsurvivalgear.com/img/products/tent.jpg
  url: /shop/shelter/tent/
  category: Shelter
  categoryurl: /shop/shelter
