- name: Flint and steel
  price: 29.99
  slug: flint-and-steel
  sku: FAS
  image: http://d.gr-assets.com/books/1333576876l/10127019.jpg
  url: /shop/firemaking/flint-and-steel
  category: Firemaking
  categoryurl: /shop/firemaking

- name: Lighter
  price: 29.99
  slug: lighter
  sku: L
  image: http://d.gr-assets.com/books/1333576876l/10127019.jpg
  url: /shop/firemaking/lighter
  category: Firemaking
  categoryurl: /shop/firemaking

- name: Canned ravioli
  price: 20.99
  slug: canned-ravioli
  sku: CR
  image: http://d.gr-assets.com/books/1422538855l/23158207.jpg
  url: /shop/food-and-preparation/canned-ravioli
  category: Food and preparation
  categoryurl: /shop/food-and-preparation

- name: Swiss knife
  price: 39.99
  slug: swiss-knife
  sku: SK
  image: http://d.gr-assets.com/books/1391275636l/6732019.jpg
  url: /shop/knives-and-tools/swiss-knife
  category: Knives and tools
  categoryurl: /shop/knives-and-tools

- name: First aid kit
  price: 39.99
  slug: first-aid-kit
  sku: FA
  image: http://d.gr-assets.com/books/1391275636l/6732019.jpg
  url: /shop/first-aid/first-aid-kit
  category: First aid
  categoryurl: /shop/first-aid

- name: Wax jacket
  price: 139.99
  slug: wax-jacket
  description: >
    Crafted in tonal waxed and unwaxed cotton,
    the Kitefin Slim Jacket is part of Barbour's
    exclusive collaboration with Japanese brand
    White Mountaineering. Standout features include
    leather trims, a stowaway hood and an exclusive
    fishing-inspired camo print lining.
  sku: WJ
  image: http://localhost:4000/img/products/wax-jacket.jpg
  url: /shop/clothing-and-gear/wax-jacket/
  category: Clothing and gear
  categoryurl: /shop/clothing-and-gear

- name: Tent
  price: 39.99
  slug: tent
  sku: SI
  image: ../img/products/tent.jpg
  url: /shop/shelter/tent/
  category: Shelter
  categoryurl: /shop/shelter
